export const SELECTED_ID = 'SELECTED_ID';
export const SELECTED_TAP_TYPE = 'SELECTED_TAP_TYPE';
export const BOOKMARK_LIST = 'BOOKMARK_LIST';
export const DELETE_BOOKMARK_LIST = 'SELECTED_BOOKMARK_ID';
